import { Injectable } from '@angular/core';
import { State } from './state';
import { City } from './city';
import { District } from './district';
import { Bank } from './bank';
import { Ifsc } from './ifsc';

@Injectable({
  providedIn: 'root'
})
export class CustomService {

  constructor() { }

  getStates() {
    return [
     new State('Andhra Pradesh' ),
     new State('Arunachal Pradesh' ),
     new State('Assam'),
     new State('Bihar'),
     new State('Chhattisgarh'),
     new State('Goa'),
     new State('Gujarat'),
     new State('Haryana'),
     new State('Himachal Pradesh'),
     new State('Jammu and Kashmir'),
     new State('Jharkhand'),
     new State('Karnataka'),
     new State('Kerala'),
     new State('Madya Pradesh'),
     new State('Maharashtra'),
     new State('Manipur'),
     new State('Meghalaya'),
     new State('Mizoram'),
     new State('Nagaland'),
     new State('Orissa'),
     new State('Punjab'),
     new State('Rajasthan'),
     new State('Sikkim'),
     new State('Tamil Nadu'),
     new State('Telagana'),
     new State('Tripura'),
     new State('Uttaranchal'),

     new State('Uttar Pradesh'),
     new State('West Bengal'),
    ];
  }
  
  getDistrict() {
   return [
     new District('Karnataka' ,'Bagalkot'),
     new District('Karnataka', 'Belagavi'),
     new District('Karnataka', 'Bengaluru Rural'),
     new District('Karnataka', 'Bengaluru Urban'),
     new District('Karnataka', 'Bellary'),
     new District('Karnataka', 'Bidar' ),
     new District('Karnataka', 'Chamarajnagar' ),
     new District('Karnataka', 'Chikkaballapur' ),
     new District('Karnataka', 'Chikkamagaluru' ),
     new District('Karnataka', 'Chitradurga' ),
     new District('Karnataka', 'Dakshina Kannada' ),
     new District('Karnataka', 'Davanagere' ),
     new District('Karnataka', 'Dharwad' ),
     new District('Karnataka', 'Gadag' ),
     new District('Karnataka', 'Hassan' ),
     new District('Karnataka', 'Haveri' ),
     new District('Karnataka', 'Kalaburagi' ),
     new District('Karnataka', 'Kodagu' ),
     new District('Karnataka', 'Kolar' ),
     new District('Karnataka', 'Koppal' ),
     new District('Karnataka', 'Mandya' ),
     new District('Karnataka', 'Mysuru' ),
     new District('Karnataka', 'Raichur' ),
     new District('Karnataka', 'Ramanagara' ),
     new District('Karnataka', 'Shivamogga' ),
     new District('Karnataka', 'Tumakuru' ),
     new District('Karnataka', 'Udupi' ),
     new District('Karnataka', 'Uttara Kannada' ),
     new District('Karnataka', 'Vijayapura' ),
     new District('Karnataka', 'Yadgir'),
     //andrapradesh
     new District('Andhra Pradesh', 'Ananthapur district'),
     new District('Andhra Pradesh', 'Kadapa district'),
     new District('Andhra Pradesh', 'Prakasam district'),
     new District('Andhra Pradesh', 'West Godavari district'),
     new District('Andhra Pradesh', 'Chittor district'),
     new District('Andhra Pradesh', 'Srikakulam district'),
     new District('Andhra Pradesh', 'Nellore district'),
     new District('Andhra Pradesh', 'East Godavari district'),
     new District('Andhra Pradesh', 'Vizianagaram district'),
     new District('Andhra Pradesh', 'Kurnool district'),
     new District('Andhra Pradesh', 'Visakhapatanam district'),
     new District('Andhra Pradesh', 'krishna district'),
     new District('Andhra Pradesh', 'Guntur district'),
     //Arunachalpradhesh
     new District('Arunachal Pradesh', 'Anjaw'),
     new District('Arunachal Pradesh', 'Changlang'),
     new District('Arunachal Pradesh', 'East Kameng'),
     new District('Arunachal Pradesh', 'East Siang'),
     new District('Arunachal Pradesh', 'Kamle'),
     new District('Arunachal Pradesh', 'Kra Daadi'),
     new District('Arunachal Pradesh', 'Kurung Kumey'),
     new District('Arunachal Pradesh', 'Lepa-Rada'),
     new District('Arunachal Pradesh', 'Lohit'),
     new District('Arunachal Pradesh', 'Longding'),
     new District('Arunachal Pradesh', 'Lower Dibang Valley'),
     new District('Arunachal Pradesh', 'Lower Siang'),
     new District('Arunachal Pradesh', 'Lower Subansiri'),
     new District('Arunachal Pradesh', 'Namsai'),
     new District('Arunachal Pradesh', 'Pakke-Kessang'),
     new District('Arunachal Pradesh', 'Papum Pare'),
     new District('Arunachal Pradesh', 'Shi-Yomi'),
     new District('Arunachal Pradesh', 'Siang'),
     new District('Arunachal Pradesh', 'Tawang'),
     new District('Arunachal Pradesh', 'Tirap'),
     new District('Arunachal Pradesh', 'Upper Dibang Valley'),
     new District('Arunachal Pradesh', 'Upper Siang'),
     new District('Arunachal Pradesh', 'Upper Subansiri'),
     new District('Arunachal Pradesh', 'West Kameng'),
     new District('Arunachal Pradesh', 'West Siang'),
     //Assam
     new District('Assam', 'Baksa'),
     new District('Assam', 'Barpeta'),
     new District('Assam', 'Biswanath'),
     new District('Assam', 'Bongaigaon'),
     new District('Assam', 'Cachar'),
     new District('Assam', 'Charaideo'),
     new District('Assam', 'Chirang'),
     new District('Assam', 'Darrang'),
     new District('Assam', 'Dhemaji'),
     new District('Assam', 'Dhubri'),
     new District('Assam', 'Dibrugarh'),
     new District('Assam', 'Dima Hasao'),
     new District('Assam', 'Goalpara'),
     new District('Assam', 'Golaghat'),
     new District('Assam', 'Hailakandi'),
     new District('Assam', 'Hojai'),
     new District('Assam', 'Jorhat'),
     new District('Assam', 'Kamrup Metropolitan'),
     new District('Assam', 'Kamrup'),
     new District('Assam', 'Karbi Anglong'),
     new District('Assam', 'Karimganj'),
     new District('Assam', 'Kokrajhar'),
     new District('Assam', 'Lakhimpur'),
     new District('Assam', 'Majuli'),
     new District('Assam', 'Morigaon'),
     new District('Assam', 'Nagaon'),
     new District('Assam', 'Nalbari'),
     new District('Assam', 'Sivasagar'),
     new District('Assam', 'Sonitpur'),
     new District('Assam', 'South Salmara-Mankachar'),
     new District('Assam', 'Tinsukia'),
     new District('Assam', 'Udalguri'),
     new District('Assam', 'West Karbi Anglong'),
     //Bihar
     new District('Bihar', 'Araria'),
     new District('Bihar', 'Arwal'),
     new District('Bihar', 'Aurangabad'),
     new District('Bihar', 'Banka'),
     new District('Bihar', 'Begusarai'),
     new District('Bihar', 'Bhagalpur'),
     new District('Bihar', 'Bhojpur'),
     new District('Bihar', 'Buxar'),
     new District('Bihar', 'Darbhanga'),
     new District('Bihar', 'East Champaran'),
     new District('Bihar', 'Gaya'),
     new District('Bihar', 'Gopalganj'),
     new District('Bihar', 'Jamui'),
     new District('Bihar', 'Jehanabad'),
     new District('Bihar', 'Kaimur'),
     new District('Bihar', 'Katihar'),
     new District('Bihar', 'Khagaria'),
     new District('Bihar', 'Kishanganj'),
     new District('Bihar', 'Lakhisarai'),
     new District('Bihar', 'Madhepura'),
     new District('Bihar', 'Madhubani'),
     new District('Bihar', 'Munger'),
     new District('Bihar', 'Muzaffarpur'),
     new District('Bihar', 'Nalanda'),
     new District('Bihar', 'Nawada'),
     new District('Bihar', 'Patna'),
     new District('Bihar', 'Purnia'),
     new District('Bihar', 'Rohtas'),
     new District('Bihar', 'Saharsa'),
     new District('Bihar', 'Samastipur'),
     new District('Bihar', 'Saran'),
     new District('Bihar', 'Sheikhpura'),
     new District('Bihar', 'Sheohar'),
     new District('Bihar', 'Sitamarhi'),
     new District('Bihar', 'Siwan'),
     new District('Bihar', 'Supaul'),
     new District('Bihar', 'Vaishali'),
     new District('Bihar', 'West Champaran'),
     //Chhattisgarh
     new District('Chhattisgarh', 'Balod'),
     new District('Chhattisgarh', 'Baloda Bazar'),
     new District('Chhattisgarh', 'Balrampur'),
     new District('Chhattisgarh', 'Bastar'),
     new District('Chhattisgarh', 'Bemetara'),
     new District('Chhattisgarh', 'Bijapur'),
     new District('Chhattisgarh', 'Bilaspur'),
     new District('Chhattisgarh', 'Dantewada'),
     new District('Chhattisgarh', 'Dhamtari'),
     new District('Chhattisgarh', 'Durg'),
     new District('Chhattisgarh', 'Gariaband'),
     new District('Chhattisgarh', 'Janjgir-Champa'),
     new District('Chhattisgarh', 'Jashpur'),
     new District('Chhattisgarh', 'Kabirdham'),
     new District('Chhattisgarh', 'Kanker'),
     new District('Chhattisgarh', 'Kondagaon'),
     new District('Chhattisgarh', 'Korba'),
     new District('Chhattisgarh', 'Koriya'),
     new District('Chhattisgarh', 'Mahasamund'),
     new District('Chhattisgarh', 'Mungeli'),
     new District('Chhattisgarh', 'Narayanpur'),
     new District('Chhattisgarh', 'Raigarh'),
     new District('Chhattisgarh', 'Raipur'),
     new District('Chhattisgarh', 'Rajnandgaon'),
     new District('Chhattisgarh', 'Sukma'),
     new District('Chhattisgarh', 'Surajpur'),
     new District('Chhattisgarh', 'Surguja'),
     //Goa
     new District('Goa', 'North Goa'),
     new District('Goa', 'South Goa'),
     //Gujarat
     new District('Gujarat', 'Ahmedabad'),
     new District('Gujarat', 'Amreli'),
     new District('Gujarat', 'Anand'),
     new District('Gujarat', 'Aravalli'),
     new District('Gujarat', 'Banaskantha'),
     new District('Gujarat', 'Bharuch'),
     new District('Gujarat', 'Bhavnagar'),
     new District('Gujarat', 'Botad'),
     new District('Gujarat', 'Chhota Udaipur'),
     new District('Gujarat', 'Dahod'),
     new District('Gujarat', 'Dang'),
     new District('Gujarat', 'Devbhoomi Dwarka'),
     new District('Gujarat', 'Gandhinagar'),
     new District('Gujarat', 'Gir Somnath'),
     new District('Gujarat', 'Jamnagar'),
     new District('Gujarat', 'Junagadh'),
     new District('Gujarat', 'Kutch'),
     new District('Gujarat', 'Kheda'),
     new District('Gujarat', 'Mahisagar'),
     new District('Gujarat', 'Mehsana'),
     new District('Gujarat', 'Morbi'),
     new District('Gujarat', 'Narmada'),
     new District('Gujarat', 'Navsari'),
     new District('Gujarat', 'Panchmahal'),
     new District('Gujarat', 'Patan'),
     new District('Gujarat', 'Porbandar'),
     new District('Gujarat', 'Rajkot'),
     new District('Gujarat', 'Sabarkantha'),
     new District('Gujarat', 'Surat'),
     new District('Gujarat', 'Surendranagar'),
     new District('Gujarat', 'Tapi'),
     new District('Gujarat', 'Vadodara'),
     new District('Gujarat', 'Valsad'),
     //Haryana
     new District('Haryana', 'Ambala'),
     new District('Haryana', 'Bhiwani'),
     new District('Haryana', 'Charkhi Dadri'),
     new District('Haryana', 'Faridabad'),
     new District('Haryana', 'Fatehabad'),
     new District('Haryana', 'Gurugram'),
     new District('Haryana', 'Hisar'),
     new District('Haryana', 'Jhajjar'),
     new District('Haryana', 'Jind'),
     new District('Haryana', 'Kaithal'),
     new District('Haryana', 'Karnal'),
     new District('Haryana', 'Kurukshetra'),
     new District('Haryana', 'Mahendragarh'),
     new District('Haryana', 'Nuh'),
     new District('Haryana', 'Palwal'),
     new District('Haryana', 'Panchkula'),
     new District('Haryana', 'Panipat'),
     new District('Haryana', 'Rewari'),
     new District('Haryana', 'Rohtak'),
     new District('Haryana', 'Sirsa'),
     new District('Haryana', 'Sonipat'),
     new District('Haryana', 'Yamunanagar'),
     //Himachalpradhesh
     new District('Himachal Pradesh', 'Bilaspur'),
     new District('Himachal Pradesh', 'Chamba'),
     new District('Himachal Pradesh', 'Hamirpur'),
     new District('Himachal Pradesh', 'Kangra'),
     new District('Himachal Pradesh', 'Kinnaur'),
     new District('Himachal Pradesh', 'Kullu'),
     new District('Himachal Pradesh', 'Lahaul and Spiti'),
     new District('Himachal Pradesh', 'Mandi'),
     new District('Himachal Pradesh', 'Shimla'),
     new District('Himachal Pradesh', 'Sirmaur'),
     new District('Himachal Pradesh', 'Solan'),
     new District('Himachal Pradesh', 'Una'),
     //Jammuandkashmir
     new District('Jammu and Kashmir', 'Doda District'),
     new District('Jammu and Kashmir', 'Jammu District'),
     new District('Jammu and Kashmir', 'Kathua District'),
     new District('Jammu and Kashmir', 'Kishtwar District'),
     new District('Jammu and Kashmir', 'Poonch District'),
     new District('Jammu and Kashmir', 'Rajouri District'),
     new District('Jammu and Kashmir', 'Ramban District'),
     new District('Jammu and Kashmir', 'Reasi District'),
     new District('Jammu and Kashmir', 'Samba District'),
     new District('Jammu and Kashmir', 'Udhampur District'),
     //Jharkhand
     new District('Jharkhand', 'Bokaro'),
     new District('Jharkhand', 'Chatra'),
     new District('Jharkhand', 'Deoghar'),
     new District('Jharkhand', 'Dhanbad'),
     new District('Jharkhand', 'Dumka'),
     new District('Jharkhand', 'East Singhbhum'),
     new District('Jharkhand', 'Garhwa'),
     new District('Jharkhand', 'Giridih'),
     new District('Jharkhand', 'Godda'),
     new District('Jharkhand', 'Gumla'),
     new District('Jharkhand', 'Hazaribagh'),
     new District('Jharkhand', 'Jamtara'),
     new District('Jharkhand', 'Khunti'),
     new District('Jharkhand', 'Koderma'),
     new District('Jharkhand', 'Latehar'),
     new District('Jharkhand', 'Lohardaga'),
     new District('Jharkhand', 'Pakur'),
     new District('Jharkhand', 'Palamu'),
     new District('Jharkhand', 'Ramgarh'),
     new District('Jharkhand', 'Ranchi'),
     new District('Jharkhand', 'Sahibganj'),
     new District('Jharkhand', 'Simdega'),
     new District('Jharkhand', 'West Singhbhum'),
     new District('Jharkhand', 'Seraikella Kharsawan'),
     //Kerala
     new District('Kerala', 'Alappuzha'),
     new District('Kerala', 'Ernakulam'),
     new District('Kerala', 'Idukki'),
     new District('Kerala', 'Kannur'),
     new District('Kerala', 'Kasaragod'),
     new District('Kerala', 'Kollam'),
     new District('Kerala', 'Kottayam'),
     new District('Kerala', 'Kozhikode'),
     new District('Kerala', 'Malappuram'),
     new District('Kerala', 'Palakkad'),
     new District('Kerala', 'Pathanamthitta'),
     new District('Kerala', 'Thiruvananthapuram'),
     new District('Kerala', 'Thrissur'),
     new District('Kerala', 'Wayanad'),
     //madhyapradhesh
     new District('Madhya Pradesh', 'Agar Malwa'),
     new District('Madhya Pradesh', 'Alirajpur'),
     new District('Madhya Pradesh', 'Anuppur'),
     new District('Madhya Pradesh', 'Ashoknagar'),
     new District('Madhya Pradesh', 'Balaghat'),
     new District('Madhya Pradesh', 'Barwani'),
     new District('Madhya Pradesh', 'Betul'),
     new District('Madhya Pradesh', 'Bhind'),
     new District('Madhya Pradesh', 'Bhopal'),
     new District('Madhya Pradesh', 'Burhanpur'),
     new District('Madhya Pradesh', 'Chhatarpur'),
     new District('Madhya Pradesh', 'Chhatarpur'),
     new District('Madhya Pradesh', 'Damoh'),
     new District('Madhya Pradesh', 'Datia'),
     new District('Madhya Pradesh', 'Dewas'),
     new District('Madhya Pradesh', 'Dhar'),
     new District('Madhya Pradesh', 'Dindori'),
     new District('Madhya Pradesh', 'Guna'),
     new District('Madhya Pradesh', 'Gwalior'),
     new District('Madhya Pradesh', 'Harda'),
     new District('Madhya Pradesh', 'Hoshangabad'),
     new District('Madhya Pradesh', 'Indore'),
     new District('Madhya Pradesh', 'Jabalpur'),
     new District('Madhya Pradesh', 'Jhabua'),
     new District('Madhya Pradesh', 'Katni'),
     new District('Madhya Pradesh', 'Khandwa'),
     new District('Madhya Pradesh', 'Khargone'),
     new District('Madhya Pradesh', 'Mandla'),
     new District('Madhya Pradesh', 'Mandsaur'),
     new District('Madhya Pradesh', 'Morena'),
     new District('Madhya Pradesh', 'Narsinghpur'),
     new District('Madhya Pradesh', 'Neemuch'),
     new District('Madhya Pradesh', 'Panna'),
     new District('Madhya Pradesh', 'Raisen'),
     new District('Madhya Pradesh', 'Rajgarh'),
     new District('Madhya Pradesh', 'Ratlam'),
     new District('Madhya Pradesh', 'Rewa'),
     new District('Madhya Pradesh', 'Sagar'),
     new District('Madhya Pradesh', 'Satna'),
     new District('Madhya Pradesh', 'Sehore'),
     new District('Madhya Pradesh', 'Seoni'),
     new District('Madhya Pradesh', 'Shahdol'),
     new District('Madhya Pradesh', 'Shajapur'),
     new District('Madhya Pradesh', 'Sheopur'),
     new District('Madhya Pradesh', 'Shivpuri'),
     new District('Madhya Pradesh', 'Sidhi'),
     new District('Madhya Pradesh', 'Singrauli'),
     new District('Madhya Pradesh', 'Tikamgarh'),
     new District('Madhya Pradesh', 'Ujjain'),
     new District('Madhya Pradesh', 'Umaria'),
     new District('Madhya Pradesh', 'Vidisha'),
     //Maharashtra
     new District('Maharashtra', 'Ahmednagar'),
     new District('Maharashtra', 'Akola'),
     new District('Maharashtra', 'Amravati'),
     new District('Maharashtra', 'Aurangabad'),
     new District('Maharashtra', 'Beed'),
     new District('Maharashtra', 'Bhandara'),
     new District('Maharashtra', 'Buldhana'),
     new District('Maharashtra', 'Chandrapur'),
     new District('Maharashtra', 'Dhule'),
     new District('Maharashtra', 'Gadchiroli'),
     new District('Maharashtra', 'Gondia'),
     new District('Maharashtra', 'Hingoli'),
     new District('Maharashtra', 'Jalgaon'),
     new District('Maharashtra', 'Jalna'),
     new District('Maharashtra', 'Kolhapur'),
     new District('Maharashtra', 'Latur'),
     new District('Maharashtra', 'Mumbai City'),
     new District('Maharashtra', 'Mumbai Suburban'),
     new District('Maharashtra', 'Nagpur'),
     new District('Maharashtra', 'Nanded'),
     new District('Maharashtra', 'Nandurbar'),
     new District('Maharashtra', 'Nashik'),
     new District('Maharashtra', 'Osmanabad'),
     new District('Maharashtra', 'Parbhani'),
     new District('Maharashtra', 'Pune'),
     new District('Maharashtra', 'Raigad'),
     new District('Maharashtra', 'Ratnagiri'),
     new District('Maharashtra', 'Sangli'),
     new District('Maharashtra', 'Satara'),
     new District('Maharashtra', 'Sindhudurg'),
     new District('Maharashtra', 'Solapur'),
     new District('Maharashtra', 'Thane'),
     new District('Maharashtra', 'Wardha'),
     new District('Maharashtra', 'Washim'),
     new District('Maharashtra', 'Yavatmal'),
     new District('Maharashtra', 'Palghar'),
     //Manipur
     new District('Manipur', 'Bishnupur'),
     new District('Manipur', 'Thoubal'),
     new District('Manipur', 'Imphal East'),
     new District('Manipur', 'Imphal West'),
     new District('Manipur', 'Senapati'),
     new District('Manipur', 'Ukhrul'),
     new District('Manipur', 'Chandel'),
     new District('Manipur', 'Churachandpur'),
     new District('Manipur', 'Tamenglong'),
     new District('Manipur', 'Jiribam'),
     new District('Manipur', 'Kangpokpi (Sadar Hills)'),
     new District('Manipur', 'Kakching'),
     new District('Manipur', 'Tengnoupal'),
     new District('Manipur', 'Kamjong'),
     new District('Manipur', 'Noney'),
     new District('Manipur', 'Pherzawl'),
     //Meghalaya
     new District('Meghalaya', 'East Garo Hills'),
     new District('Meghalaya', 'East Jaintia Hills'),
     new District('Meghalaya', 'East Khasi Hills'),
     new District('Meghalaya', 'North Garo Hills'),
     new District('Meghalaya', 'Ri Bhoi'),
     new District('Meghalaya', 'South Garo Hills'),
     new District('Meghalaya', 'South West Garo Hills'),
     new District('Meghalaya', 'South West Khasi Hills'),
     new District('Meghalaya', 'West Garo Hills'),
     new District('Meghalaya', 'West Jaintia Hills'),
     new District('Meghalaya', 'West Khasi Hills'),
     //mizoram
     new District('Mizoram', 'Aizawl'),
     new District('Mizoram', 'Kolasib'),
     new District('Mizoram', 'Lawngtlai'),
     new District('Mizoram', 'Lunglei'),
     new District('Mizoram', 'Mamit'),
     new District('Mizoram', 'Saiha'),
     new District('Mizoram', 'Serchhip'),
     new District('Mizoram', 'Champhai'),
     //Nagaland
     new District('Nagaland', 'Dimapur district'),
     new District('Nagaland', 'Kiphire district'),
     new District('Nagaland', 'Kohima district'),
     new District('Nagaland', 'Longleng district'),
     new District('Nagaland', 'Mokokchung district'),
     new District('Nagaland', 'Mon District'),
     new District('Nagaland', 'Peren district'),
     new District('Nagaland', 'Phek district'),
     new District('Nagaland', 'Tuensang district'),
     new District('Nagaland', 'Wokha district'),
     new District('Nagaland', 'Zunheboto district'),
     new District('Nagaland', 'Noklak district'),
     //Orissa
     new District('Orissa', 'Angul'),
     new District('Orissa', 'Boudh (Baudh)'),
     new District('Orissa', 'Balangir'),
     new District('Orissa', 'Bargarh'),
     new District('Orissa', 'Balasore (Baleswar)'),
     new District('Orissa', 'Bhadrak'),
     new District('Orissa', 'Cuttack'),
     new District('Orissa', 'Deogarh (Debagarh)'),
     new District('Orissa', 'Dhenkanal'),
     new District('Orissa', 'Ganjam'),
     new District('Orissa', 'Gajapati'),
     new District('Orissa', 'Jharsuguda'),
     new District('Orissa', 'Jajpur'),
     new District('Orissa', 'Jagatsinghapur'),
     new District('Orissa', 'Khordha'),
     new District('Orissa', 'Keonjhar (Kendujhar)'),
     new District('Orissa', 'Kalahandi'),
     new District('Orissa', 'Kandhamal'),
     new District('Orissa', 'Koraput'),
     new District('Orissa', 'Kendrapara'),
     new District('Orissa', 'Malkangiri'),
     new District('Orissa', 'Mayurbhanj'),
     new District('Orissa', 'Nabarangpur'),
     new District('Orissa', 'Nuapada'),
     new District('Orissa', 'Nayagarh'),
     new District('Orissa', 'Puri'),
     new District('Orissa', 'Rayagada'),
     new District('Orissa', 'Sambalpur'),
     new District('Orissa', 'Subarnapur (Sonepur)'),
     new District('Orissa', 'Sundargarh'),
     //Punjab
     new District('Punjab', 'Amritsar'),
     new District('Punjab', 'Barnala'),
     new District('Punjab', 'Bathinda'),
     new District('Punjab', 'Faridkot'),
     new District('Punjab', 'Fatehgarh Sahib'),
     new District('Punjab', 'Firozpur'),
     new District('Punjab', 'Fazilka'),
     new District('Punjab', 'Gurdaspur'),
     new District('Punjab', 'Hoshiarpur'),
     new District('Punjab', 'Jalandhar'),
     new District('Punjab', 'Kapurthala'),
     new District('Punjab', 'Ludhiana'),
     new District('Punjab', 'Mansa'),
     new District('Punjab', 'Moga'),
     new District('Punjab', 'Sri Muktsar Sahib'),
     new District('Punjab', 'Pathankot'),
     new District('Punjab', 'Patiala'),
     new District('Punjab', 'Rupnagar'),
     new District('Punjab', 'Sahibzada Ajit Singh Nagar'),
     new District('Punjab', 'Sangrur'),
     new District('Punjab', 'Shahid Bhagat Singh Nagar'),
     new District('Punjab', 'Taran Taran'),
     //Rajasthan
     new District('Rajasthan', 'Ajmer'),
     new District('Rajasthan', 'Alwar'),
     new District('Rajasthan', 'Banswara'),
     new District('Rajasthan', 'Baran'),
     new District('Rajasthan', 'Barmer'),
     new District('Rajasthan', 'Bharatpur'),
     new District('Rajasthan', 'Bhilwara'),
     new District('Rajasthan', 'Bikaner'),
     new District('Rajasthan', 'Bundi'),
     new District('Rajasthan', 'Chittorgarh'),
     new District('Rajasthan', 'Churu'),
     new District('Rajasthan', 'Dausa'),
     new District('Rajasthan', 'Dholpur'),
     new District('Rajasthan', 'Dungarpur'),
     new District('Rajasthan', 'Hanumangarh'),
     new District('Rajasthan', 'Jaipur'),
     new District('Rajasthan', 'Jaisalmer'),
     new District('Rajasthan', 'Jalor'),
     new District('Rajasthan', 'Jhalawar'),
     new District('Rajasthan', 'Jhunjhunu'),
     new District('Rajasthan', 'Jodhpur'),
     new District('Rajasthan', 'Karauli'),
     new District('Rajasthan', 'Kota'),
     new District('Rajasthan', 'Nagaur'),
     new District('Rajasthan', 'Pali'),
     new District('Rajasthan', 'Pratapgarh'),
     new District('Rajasthan', 'Rajsamand'),
     new District('Rajasthan', 'Sawai Madhopur'),
     new District('Rajasthan', 'Sikar'),
     new District('Rajasthan', 'Sirohi'),
     new District('Rajasthan', 'Sri Ganganagar'),
     new District('Rajasthan', 'Tonk'),
     new District('Rajasthan', 'Udaipur'),
     //Sikkim
     new District('Sikkim', 'East Sikkim'),
     new District('Sikkim', 'North Sikkim'),
     new District('Sikkim', 'South Sikkim'),
     new District('Sikkim', 'West Sikkim'),
     //TamilNadu
     new District('Tamil Nadu', 'Ariyalur'),
     new District('Tamil Nadu', 'Chennai'),
     new District('Tamil Nadu', 'Coimbatore'),
     new District('Tamil Nadu', 'Cuddalore'),
     new District('Tamil Nadu', 'Dharmapuri'),
     new District('Tamil Nadu', 'Dindigul'),
     new District('Tamil Nadu', 'Erode'),
     new District('Tamil Nadu', 'Kanchipuram'),
     new District('Tamil Nadu', 'Kanniyakumari'),
     new District('Tamil Nadu', 'Karur'),
     new District('Tamil Nadu', 'Krishnagiri'),
     new District('Tamil Nadu', 'Madurai'),
     new District('Tamil Nadu', 'Nagapattinam'),
     new District('Tamil Nadu', 'Namakkal'),
     new District('Tamil Nadu', 'Nilgiris'),
     new District('Tamil Nadu', 'Perambalur'),
     new District('Tamil Nadu', 'Pudukkottai'),
     new District('Tamil Nadu', 'Ramanathapuram'),
     new District('Tamil Nadu', 'Salem'),
     new District('Tamil Nadu', 'Sivaganga'),
     new District('Tamil Nadu', 'Thanjavur'),
     new District('Tamil Nadu', 'Theni'),
     new District('Tamil Nadu', 'Thoothukudi'),
     new District('Tamil Nadu', 'Tiruchirappalli'),
     new District('Tamil Nadu', 'Tirunelveli'),
     new District('Tamil Nadu', 'Tiruppur'),
     new District('Tamil Nadu', 'Tiruvallur'),
     new District('Tamil Nadu', 'Tiruvannamalai'),
     new District('Tamil Nadu', 'Tiruvarur'),
     new District('Tamil Nadu', 'Vellore'),
     new District('Tamil Nadu', 'Viluppuram'),
     //Telangana
     new District('Telagana', 'Adilabad'),
     new District('Telagana', 'Bhadradri Kothagudem'),
     new District('Telagana', 'Hyderabad'),
     new District('Telagana', 'Jagtial'),
     new District('Telagana', 'Jangaon'),
     new District('Telagana', 'Jayashankar Bhupalapally'),
     new District('Telagana', 'Jogulamba Gadwal'),
     new District('Telagana', 'Kamareddy'),
     new District('Telagana', 'Karimnagar'),
     new District('Telagana', 'Khammam'),
     new District('Telagana', 'Kumarambheem Asifabad'),
     new District('Telagana', 'Mahabubabad'),
     new District('Telagana', 'Mahabubnagar'),
     new District('Telagana', 'Mancherial'),
     new District('Telagana', 'Medak'),
     new District('Telagana', 'Medchal–Malkajgiri'),
     new District('Telagana', 'Nagarkurnool'),
     new District('Telagana', 'Nalgonda'),
     new District('Telagana', 'Nirmal'),
     new District('Telagana', 'Nizamabad'),
     new District('Telagana', 'Peddapalli'),
     new District('Telagana', 'Rajanna Sircilla'),
     new District('Telagana', 'Ranga Reddy'),
     new District('Telagana', 'Sangareddy'),
     new District('Telagana', 'Siddipet'),
     new District('Telagana', 'Suryapet'),
     new District('Telagana', 'Vikarabad'),
     new District('Telagana', 'Wanaparthy'),
     new District('Telagana', 'Warangal Rural'),
     new District('Telagana', 'Warangal Urban'),
     new District('Telagana', 'Yadadri Bhuvanagiri'),
     //Tripura
     new District('Tripura', 'Dhalai'),
     new District('Tripura', 'North Tripura'),
     new District('Tripura', 'South Tripura'),
     new District('Tripura', 'West Tripura'),
     //Uttarakhand
     new District('Uttarakhand', 'Almora'),
     new District('Uttarakhand', 'Bageshwar'),
     new District('Uttarakhand', 'Chamoli'),
     new District('Uttarakhand', 'Champawat'),
     new District('Uttarakhand', 'Dehradun'),
     new District('Uttarakhand', 'Haridwar'),
     new District('Uttarakhand', 'Nainital'),
     new District('Uttarakhand', 'Pauri Garhwal'),
     new District('Uttarakhand', 'Pithoragarh'),
     new District('Uttarakhand', 'Rudraprayag'),
     new District('Uttarakhand', 'Tehri Garhwal'),
     new District('Uttarakhand', 'Udham Singh Nagar'),
     new District('Uttarakhand', 'Uttarkashi'),
     //Uttarpradhesh
     new District('Uttar Pradesh', 'Agra'),
     new District('Uttar Pradesh', 'Aligarh'),
     new District('Uttar Pradesh', 'Allahabad'),
     new District('Uttar Pradesh', 'Ambedkar Nagar'),
     new District('Uttar Pradesh', 'Amroha'),
     new District('Uttar Pradesh', 'Auraiya'),
     new District('Uttar Pradesh', 'Azamgarh'),
     new District('Uttar Pradesh', 'Badaun'),
     new District('Uttar Pradesh', 'Bahraich'),
     new District('Uttar Pradesh', 'Ballia'),
     new District('Uttar Pradesh', 'Balrampur'),
     new District('Uttar Pradesh', 'Banda District'),
     new District('Uttar Pradesh', 'Barabanki'),
     new District('Uttar Pradesh', 'Bareilly'),
     new District('Uttar Pradesh', 'Basti'),
     new District('Uttar Pradesh', 'Bijnor'),
     new District('Uttar Pradesh', 'Bulandshahr'),
     new District('Uttar Pradesh', 'Chandauli'),
     new District('Uttar Pradesh', 'Chitrakoot'),
     new District('Uttar Pradesh', 'Deoria'),
     new District('Uttar Pradesh', 'Etah'),
     new District('Uttar Pradesh', 'Etawah'),
     new District('Uttar Pradesh', 'Faizabad'),
     new District('Uttar Pradesh', 'Farrukhabad'),
     new District('Uttar Pradesh', 'Fatehpur'),
     new District('Uttar Pradesh', 'Firozabad'),
     new District('Uttar Pradesh', 'Gautam Buddha Nagar'),
     new District('Uttar Pradesh', 'Ghaziabad'),
     new District('Uttar Pradesh', 'Ghazipur'),
     new District('Uttar Pradesh', 'Gonda'),
     new District('Uttar Pradesh', 'Gorakhpur'),
     new District('Uttar Pradesh', 'Hamirpur'),
     new District('Uttar Pradesh', 'Hapur District'),
     new District('Uttar Pradesh', 'Hardoi'),
     new District('Uttar Pradesh', 'Hathras'),
     new District('Uttar Pradesh', 'Jaunpur District'),
     new District('Uttar Pradesh', 'Jhansi'),
     new District('Uttar Pradesh', 'Kannauj'),
     new District('Uttar Pradesh', 'Kanpur Dehat'),
     new District('Uttar Pradesh', 'Kanpur Nagar'),
     new District('Uttar Pradesh', 'Kasganj'),
     new District('Uttar Pradesh', 'Kaushambi'),
     new District('Uttar Pradesh', 'Kushinagar'),
     new District('Uttar Pradesh', 'Lakhimpur Kheri'),
     new District('Uttar Pradesh', 'Lalitpur'),
     new District('Uttar Pradesh', 'Lucknow'),
     new District('Uttar Pradesh', 'Maharajganj'),
     new District('Uttar Pradesh', 'Mahoba'),
     new District('Uttar Pradesh', 'Mainpuri'),
     new District('Uttar Pradesh', 'Mathura'),
     new District('Uttar Pradesh', 'Mau'),
     new District('Uttar Pradesh', 'Meerut'),
     new District('Uttar Pradesh', 'Mirzapur'),
     new District('Uttar Pradesh', 'Moradabad'),
     new District('Uttar Pradesh', 'Muzaffarnagar'),
     new District('Uttar Pradesh', 'Pilibhit'),
     new District('Uttar Pradesh', 'Pratapgarh'),
     new District('Uttar Pradesh', 'Rae Bareli'),
     new District('Uttar Pradesh', 'Rampur'),
     new District('Uttar Pradesh', 'Saharanpur'),
     new District('Uttar Pradesh', 'Sant Kabir Nagar'),
     new District('Uttar Pradesh', 'Sant Ravidas Nagar'),
     new District('Uttar Pradesh', 'Sambhal'),
     new District('Uttar Pradesh', 'Shahjahanpur'),
     new District('Uttar Pradesh', 'Shamli'),
     new District('Uttar Pradesh', 'Shravasti'),
     new District('Uttar Pradesh', 'Siddharthnagar'),
     new District('Uttar Pradesh', 'Sitapur'),
     new District('Uttar Pradesh', 'Sonbhadra'),
     new District('Uttar Pradesh', 'Sultanpur'),
     new District('Uttar Pradesh', 'Unnao'),
     new District('Uttar Pradesh', 'Varanasi'),
     //Westbengal
     new District('West Bengal', 'Alipurduar'),
     new District('West Bengal', 'Bankura'),
     new District('West Bengal', 'Paschim Bardhaman'),
     new District('West Bengal', 'Purba Bardhaman'),
     new District('West Bengal', 'Birbhum'),
     new District('West Bengal', 'Cooch Behar'),
     new District('West Bengal', 'Darjeeling'),
     new District('West Bengal', 'Uttar Dinajpur'),
     new District('West Bengal', 'Dakshin Dinajpur'),
     new District('West Bengal', 'Hooghly'),
     new District('West Bengal', 'Howrah'),
     new District('West Bengal', 'Jalpaiguri'),
     new District('West Bengal', 'Jhargram'),
     new District('West Bengal', 'Kolkata'),
     new District('West Bengal', 'Kalimpong'),
     new District('West Bengal', 'Malda'),
     new District('West Bengal', 'Paschim Medinipur'),
     new District('West Bengal', 'Purba Medinipur'),
     new District('West Bengal', 'Murshidabad'),
     new District('West Bengal', 'Nadia'),
     new District('West Bengal', 'North 24 Parganas'),
     new District('West Bengal', 'South 24 Parganas'),
     new District('West Bengal', 'Purulia'),
     
    ];
  
  }
  
  
  getCities() {
   return [
     new City('Bagalkot' ,'Badami' ),
     new City('Bagalkot' ,'Bagalkot' ), 
     new City('Bagalkot' ,'Bilgi' ), 
     new City('Bagalkot' ,'Hungund' ), 
     new City('Bagalkot' ,'Ilkal' ),
     new City('Bagalkot' ,'Jamkhandi' ),
     new City('Bagalkot' ,'Mudhol'),
     new City('Belagavi' ,'Athni'),
     new City('Belagavi' ,'Bailahongal'),
     new City('Belagavi' ,'Belagavi'),
     new City('Belagavi' ,'Chikodi'),
     new City('Belagavi' ,'Gokak'),
     new City('Belagavi' ,'Hukkeri'),
     new City('Belagavi' ,'Khanapur'),
     new City('Belagavi' ,'Kagawad'),
     new City('Belagavi' ,'Mudalagi'),
     new City('Belagavi' ,'Nippani'),
     new City('Belagavi' ,'Kittur'),
     new City('Belagavi' ,'Raybag'),
     new City('Belagavi' ,'Ramdurg'),
     new City('Belagavi' ,'Saundatti'),
     new City('Bengaluru Urban' ,'Anekal'),
     new City('Bengaluru Urban' ,'Bengaluru North'),
     new City('Bengaluru Urban' ,' Bengaluru East'),
     new City('Bengaluru Urban' ,'Bengaluru South'),
     new City('Bengaluru Rural' ,'Devanahalli'),
     new City('Bengaluru Rural' ,'Doddaballapura'),
     new City('Bengaluru Rural' ,'Hoskote'),
     new City('Bengaluru Rural' ,'Nelamangala'),
     new City('Bellary' ,'Ballari'),
     new City('Bellary' ,'Hosapete'),
     new City('Bellary' ,'Kampli'),
     new City('Bellary' ,'Hoovina Hadagalli'),
     new City('Bellary' ,'Kudligi'),
     new City('Bellary' ,'Sanduru'),
     new City('Bellary' ,'Siruguppa'),
     new City('Bidar' ,'Bidar'),
     new City('Bidar' ,'Basavakalyan'),
     new City('Bidar' ,'Bhalki'),
     new City('Bidar' ,'Homnabad'),
     new City('Bidar' ,'Aurad'),
     new City('Chamarajnagar' ,'Chamrajnagar'),
     new City('Chamarajnagar' ,'Gundlupet'),
     new City('Chamarajnagar' ,'Kollegal'),
     new City('Chamarajnagar' ,'Yelandur'),
     new City('Chikkaballapur' ,'Bagepalli'),
     new City('Chikkaballapur' ,'Chikballapur'),
     new City('Chikkaballapur' ,'Chintamani'),
     new City('Chikkaballapur' ,'Gauribidanur'),
     new City('Chikkaballapur' ,'Gudibanda'),
     new City('Chikkaballapur' ,'Sidlaghatta'),
     new City('Chikkamagaluru' ,'Chikkamagaluru'),
     new City('Chikkamagaluru' ,'Kadur'),
     new City('Chikkamagaluru' ,'Koppa'),
     new City('Chikkamagaluru' ,'Mudigere'),
     new City('Chikkamagaluru' ,'Narasimharajapura'),
     new City('Chikkamagaluru' ,'Sringeri'),
     new City('Chikkamagaluru' ,'Tarikere'),
     new City('Chikkamagaluru' ,'Challakere'),
     new City('Chitradurga' ,'Chitradurga'),
     new City('Chitradurga' ,'Hiriyur'),
     new City('Chitradurga' ,'Holalkere'),
     new City('Chitradurga' ,'Hosadurga'),
     new City('Chitradurga' ,'Molakalmuru'),
     new City('Dakshina Kannada' ,'Bantwal'),
     new City('Dakshina Kannada' ,'Beltangadi'),
     new City('Dakshina Kannada' ,'Mangaluru'),
     new City('Dakshina Kannada' ,'Puttur'),
     new City('Dakshina Kannada' ,'Sulya'), 
         
    ];
  }

 

  getbanks() {
    return [
      new Bank('State Bank of India'),
      new Bank('Canara Bank'),
      new Bank('Allahabad Bank'),
      new Bank('Andhra Bank'),
      new Bank('Bank of India'),
      new Bank('Bank of Baroda'),
      new Bank('Bank of Maharashtra'),
      new Bank('Central Bank of India'),
      new Bank('Corporation Bank'),
      new Bank('Dena Bank'),
      new Bank('Indian Bank'),
      new Bank('Indian Overseas Bank'),
      new Bank('Oriental Bank of Commerce'),
      new Bank('Punjab & Sindh Bank'),
      new Bank('Punjab National Bank'),
      new Bank('Syndicate Bank'),
      new Bank('UCO Bank'),
      new Bank('Union Bank of India'),
      new Bank('Vijaya Bank'),
      new Bank('IDBI Bank'),
      new Bank('Bharatiya Mahila Bank'),
      new Bank('Axis Bank'),
      new Bank('Deutsche Bank'),
      new Bank('BankDhanlaxmi Bank'),
      new Bank('Federal Bank'),
      new Bank('ICICI Bank'),
      new Bank('Karnataka Bank Ltd'),
      new Bank('ING Vysya Bank'),
      new Bank('Kotak Bank'),
      new Bank('Yes Bank Ltd'),
      new Bank('Shamrao Vitthal Co-operative Bank'),
      new Bank('Others'),
     
         
     ];
   }
 

     getIfscs() {
      return [
        new Ifsc('State Bank of India','SBIN'),
        new Ifsc('Canara Bank','CNRB'),
        new Ifsc('Allahabad Bank','ALLA'),
        new Ifsc('Andhra Bank','ANDB'),
        new Ifsc('Bank of India','BKID'),
        new Ifsc('Bank of Baroda','BARB'),
        new Ifsc('Bank of Maharashtra','MAHB'),
        new Ifsc('Central Bank of India','CBIN'),
        new Ifsc('Corporation Bank','CORP'),
        new Ifsc('Dena Bank','BKDN'),
        new Ifsc('Indian Bank','IDIB'),
        new Ifsc('Indian Overseas Bank','IOBA'),
        new Ifsc('Oriental Bank of Commerce','ORBC'),
        new Ifsc('Punjab & Sindh Bank','PSIB'),
        new Ifsc('Punjab National Bank','PUNB'),
        new Ifsc('Syndicate Bank','SYNB'),
        new Ifsc('UCO Bank','UCBA'),
        new Ifsc('Union Bank of India','UBIN'),
        new Ifsc('Vijaya Bank','VIJB'),
        new Ifsc('IDBI Bank','IBKL'),
        new Ifsc('Bharatiya Mahila Bank','BMBL'),
        new Ifsc('Axis Bank','UTIB'),
        new Ifsc('Deutsche Bank','DEUT'),
        new Ifsc('Dhanlaxmi Bank','DLXB'),
        new Ifsc('Federal Bank','FDRL'),
        new Ifsc('ICICI Bank','ICIC'),
        new Ifsc('Karnataka Bank Ltd','KARB'),
        new Ifsc('ING Vysya Bank','VYSA'),
        new Ifsc('Kotak Bank','KKBK'),
        new Ifsc('Yes Bank Ltd','YESB'),
        new Ifsc('Shamrao Vitthal Co-operative Bank','SVCB'),     
       ];
     }
 

}
